### ISSUE TITLE
Doesn't support lwjgl 3

### ISSUE THREAD

**Issue by Wyn-Price** [JackGoldsworth/HwkEngine#1]

**Comment by Wyn-Price** [comment]
Btw, I followed ThinMatrix's tutorial a while ago and it didn't really help anything. You have to get a couple episodes in before he starts explaining all the gl calls and shit like that. The first couple episodes are just setting up vbos and boring shit like that

**Comment by Wyn-Price** [comment]
:triumph:

**Comment by JackGoldsworth** [comment]
Oh I am well aware. Also it based on LWJGL 2.9.1, so it's fairly close to 3.0, which just makes changes to the display management and a couple of other things

**Comment by Wyn-Price** [comment]
Where do the lies end Jackaboy
![screenshot_20180812-005641](https://user-images.githubusercontent.com/15876682/43998732-c47dbd4e-9dca-11e8-8e32-bb8a3fbba52d.png)

**Comment by JackGoldsworth** [comment]
changed it you ugly man
